# Generated by Django 3.1 on 2021-05-09 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trendz', '0003_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('laptop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Trendz.laptop')),
                ('tag', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=250)),
                ('generation', models.CharField(max_length=200, null=True)),
                ('processor', models.CharField(max_length=200, null=True)),
                ('processor_speed', models.CharField(max_length=200, null=True)),
                ('installed_ram', models.CharField(max_length=200, null=True)),
                ('type_ofmemory', models.CharField(max_length=200, null=True)),
                ('hard_drivesize', models.CharField(max_length=200, null=True)),
                ('hard_drivespeed', models.CharField(max_length=200, null=True)),
                ('optical_drive', models.CharField(max_length=200, null=True)),
                ('type_ofopticaldrive', models.CharField(max_length=200, null=True)),
                ('ssd', models.CharField(max_length=200, null=True)),
                ('type_ofharddrive', models.CharField(max_length=200, null=True)),
                ('dedicated_graphics', models.CharField(max_length=200, null=True)),
                ('graphics_memory', models.CharField(max_length=200, null=True)),
                ('type_ofgraphics_memory_shared', models.CharField(max_length=200, null=True)),
                ('switchable_graphics', models.CharField(max_length=200, null=True)),
                ('graphics_processor', models.CharField(max_length=200, null=True)),
                ('backlight', models.CharField(max_length=200, null=True)),
                ('screen_size', models.CharField(max_length=200, null=True)),
                ('screen_surface', models.CharField(max_length=200, null=True)),
                ('screen_resolution', models.CharField(max_length=200, null=True)),
                ('touchscreen', models.CharField(max_length=200, null=True)),
                ('color', models.CharField(max_length=200, null=True)),
                ('fingerprint_reader', models.CharField(max_length=200, null=True)),
                ('numeric_keyboard', models.CharField(max_length=200, null=True)),
                ('backlit_keyboard', models.CharField(max_length=200, null=True)),
                ('bluetooth', models.CharField(max_length=200, null=True)),
                ('lan', models.CharField(max_length=200, null=True)),
                ('speed', models.CharField(max_length=200, null=True)),
                ('wireless_wifi', models.CharField(max_length=200, null=True)),
                ('wifi_type', models.CharField(max_length=200, null=True)),
                ('condition', models.CharField(max_length=200, null=True)),
                ('usb', models.CharField(max_length=200, null=True)),
                ('hdmi', models.CharField(max_length=200, null=True)),
                ('camera', models.CharField(max_length=200, null=True)),
                ('operating_system', models.CharField(max_length=200, null=True)),
                ('manual', models.CharField(max_length=200, null=True)),
                ('product_page', models.CharField(max_length=200, null=True)),
                ('warranty', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
