# Generated by Django 3.1 on 2021-05-11 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trendz', '0005_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobilespec',
            fields=[
                ('mobile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Trendz.mobile')),
                ('title', models.CharField(max_length=250)),
                ('tag', models.CharField(max_length=250)),
                ('camera', models.CharField(max_length=50, null=True)),
                ('processor', models.CharField(max_length=50, null=True)),
                ('internal_storage', models.CharField(max_length=50, null=True)),
                ('battery', models.CharField(max_length=50, null=True)),
                ('ram', models.CharField(max_length=50, null=True)),
                ('display', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
