# Generated by Django 3.1 on 2021-06-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trendz', '0010_mobiletrend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptoptrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('positive', models.FloatField()),
                ('negative', models.FloatField()),
                ('neutral', models.FloatField()),
            ],
        ),
    ]
