# Generated by Django 3.1 on 2021-06-26 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Trendz', '0012_laptop_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptopcomment',
            fields=[
                ('srno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trendz.laptop')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trendz.laptopcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
