# Generated by Django 3.1 on 2021-06-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trendz', '0014_laptop_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
