# Generated by Django 3.1 on 2021-06-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trendz', '0015_auto_20210629_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='title',
            field=models.CharField(max_length=350),
        ),
    ]
