# Generated by Django 3.1 on 2021-07-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trendz', '0016_auto_20210629_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='screen_surface',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
