# Generated by Django 3.1 on 2021-07-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trendz', '0017_auto_20210703_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='backlit_keyboard',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
